using Godot;
using System;
using System.Collections.Generic;

public partial class DynamicQuestSystem : BaseSystem
{
    public static DynamicQuestSystem Instance { get; private set; }
    
    // Quest types
    public enum QuestType { Combat, Collection, Exploration, Crafting, Delivery, Rescue, Hunt, Escort, Boss, Timed }
    public enum QuestDifficulty { Easy, Medium, Hard, Epic, Legendary }
    public enum QuestStatus { Available, Active, Completed, Failed }
    
    // Quest structure
    public class Quest
    {
        public string Id;
        public string Title;
        public string Description;
        public QuestType Type;
        public QuestDifficulty Difficulty;
        public QuestStatus Status;
        public int RewardGold;
        public int RewardExp;
        public int TargetCount;
        public int CurrentProgress;
        public string TargetId; // Enemy type, item id, location id
        public string Location;
        public float TimeLimit; // in seconds, 0 = no limit
        public DateTime StartTime;
        public bool IsProcedural; // Generated by PCG
    }
    
    // Quest templates for PCG
    private readonly Dictionary<QuestType, List<string>> _questTemplates = new()
    {
        { QuestType.Combat, new List<string> { 
            "Defeat {count} {enemy} in {location}",
            "Clear the {location} of {enemy}",
            "Hunt down the {enemy} threat"
        }},
        { QuestType.Collection, new List<string> {
            "Collect {count} {item} from {location}",
            "Gather {item} for the merchant",
            "Find rare {item} hidden in {location}"
        }},
        { QuestType.Exploration, new List<string> {
            "Discover all secrets in {location}",
            "Map the {location} area",
            "Find the hidden path to {location}"
        }},
        { QuestType.Crafting, new List<string> {
            "Craft {count} {item}",
            "Create {item} for the blacksmith",
            "Prepare {item} for the feast"
        }},
        { QuestType.Delivery, new List<string> {
            "Deliver {item} to {npc} in {location}",
            "Transport goods to {location}",
            "Bring {item} to {npc}"
        }},
        { QuestType.Rescue, new List<string> {
            "Rescue {npc} from {location}",
            "Save the captured {npc}",
            "Extract {npc} from danger"
        }},
        { QuestType.Hunt, new List<string> {
            "Hunt {count} {enemy} for the bounty",
            "Track and eliminate {enemy}",
            "Claim the bounty on {enemy}"
        }},
        { QuestType.Escort, new List<string> {
            "Escort {npc} safely to {location}",
            "Protect {npc} on their journey",
            "Guard {npc} to destination"
        }},
        { QuestType.Boss, new List<string> {
            "Defeat the {enemy} Boss in {location}",
            "Slay the legendary {enemy}",
            "Challenge the {enemy} Champion"
        }},
        { QuestType.Timed, new List<string> {
            "Complete {location} in under {time} seconds",
            "Race against time in {location}",
            "Survive {location} for {time} seconds"
        }}
    };
    
    // Quest data pools
    private readonly string[] _enemyTypes = { "Goblin", "Orc", "Skeleton", "Slime", "Wolf", "Spider", "Troll", "Dragon", "Demon", "Bandit" };
    private readonly string[] _itemTypes = { "Herb", "Ore", "Crystal", "Mushroom", "Gem", "Potion", "Scroll", "Weapon", "Armor" };
    private readonly string[] _locations = { "Dark Forest", "Cave of Whispers", "Ancient Ruins", "Haunted Tower", "Dragon's Lair", "Frozen Wastes", "Burning Desert", "Lost Temple" };
    private readonly string[] _npcNames = { "Elder Marcus", "Merchant Lisa", "Blacksmith John", "Healer Anna", "Guard Captain", "Village Elder", "Traveler Tom", "Mysterious Stranger" };
    
    // Active quests
    private List<Quest> _availableQuests = new();
    private List<Quest> _activeQuests = new();
    private List<Quest> _completedQuests = new();
    private List<Quest> _failedQuests = new();
    private Random _rng = new();
    private int _questCounter = 0;
    
    // Signals
    public delegate void QuestGeneratedEventHandler(Quest quest);
    public delegate void QuestStartedEventHandler(Quest quest);
    public delegate void QuestCompletedEventHandler(Quest quest);
    public delegate void QuestFailedEventHandler(Quest quest);
    public delegate void QuestProgressEventHandler(Quest quest, int progress);
    
    public override void _Ready()
    {
        Instance = this;
        base._Ready();
    }
    
    protected override void Initialize()
    {
        GenerateDailyQuests();
    }
    
    public override Dictionary<string, object> ExportSaveData()
    {
        return new Dictionary<string, object>
        {
            {"availableQuests", _availableQuests},
            {"activeQuests", _activeQuests},
            {"completedQuests", _completedQuests},
            {"failedQuests", _failedQuests},
            {"questCounter", _questCounter}
        };
    }
    
    public override void ImportSaveData(Dictionary<string, object> data)
    {
        base.ImportSaveData(data);
        if (data == null) return;
        
        if (data.ContainsKey("availableQuests")) _availableQuests = (List<Quest>)data["availableQuests"];
        if (data.ContainsKey("activeQuests")) _activeQuests = (List<Quest>)data["activeQuests"];
        if (data.ContainsKey("completedQuests")) _completedQuests = (List<Quest>)data["completedQuests"];
        if (data.ContainsKey("failedQuests")) _failedQuests = (List<Quest>)data["failedQuests"];
        if (data.ContainsKey("questCounter")) _questCounter = (int)data["questCounter"];
    }
    
    public override void _Process(double delta)
    {
        // Check timed quests
        CheckTimedQuests();
    }
    
    // PCG: Generate a random quest
    public Quest GenerateQuest(QuestType type = QuestType.Combat, QuestDifficulty difficulty = QuestDifficulty.Medium)
    {
        var quest = new Quest
        {
            Id = $"quest_{_questCounter++}_{DateTime.Now.Ticks}",
            Type = type,
            Difficulty = difficulty,
            Status = QuestStatus.Available,
            IsProcedural = true,
            CurrentProgress = 0
        };
        
        // Select template
        var templates = _questTemplates[type];
        var template = templates[_rng.Next(templates.Count)];
        
        // Fill template with random values
        quest.Title = GenerateQuestTitle(type, difficulty);
        quest.Description = GenerateQuestDescription(template);
        
        // Set parameters based on difficulty
        int baseCount = difficulty switch
        {
            QuestDifficulty.Easy => 5,
            QuestDifficulty.Medium => 10,
            QuestDifficulty.Hard => 20,
            QuestDifficulty.Epic => 35,
            QuestDifficulty.Legendary => 50,
            _ => 10
        };
        
        float difficultyMultiplier = difficulty switch
        {
            QuestDifficulty.Easy => 1.0f,
            QuestDifficulty.Medium => 1.5f,
            QuestDifficulty.Hard => 2.0f,
            QuestDifficulty.Epic => 3.0f,
            QuestDifficulty.Legendary => 5.0f,
            _ => 1.5f
        };
        
        quest.TargetCount = (int)(baseCount * (0.8f + _rng.NextSingle() * 0.4f));
        quest.TargetId = GetRandomTarget(type);
        quest.Location = _locations[_rng.Next(_locations.Length)];
        quest.RewardGold = (int)(baseCount * difficultyMultiplier * 10 * (0.8f + _rng.NextSingle() * 0.4f));
        quest.RewardExp = (int)(baseCount * difficultyMultiplier * 5 * (0.8f + _rng.NextSingle() * 0.4f));
        
        // Timed quests have time limit
        if (type == QuestType.Timed)
        {
            quest.TimeLimit = 60 + _rng.Next(300); // 1-6 minutes
        }
        
        return quest;
    }
    
    private string GenerateQuestTitle(QuestType type, QuestDifficulty difficulty)
    {
        string difficultyPrefix = difficulty switch
        {
            QuestDifficulty.Easy => "Simple",
            QuestDifficulty.Medium => "Standard",
            QuestDifficulty.Hard => "Dangerous",
            QuestDifficulty.Epic => "Epic",
            QuestDifficulty.Legendary => "Legendary",
            _ => "Standard"
        };
        
        string typeName = type switch
        {
            QuestType.Combat => "Battle",
            QuestType.Collection => "Gathering",
            QuestType.Exploration => "Exploration",
            QuestType.Crafting => "Crafting",
            QuestType.Delivery => "Delivery",
            QuestType.Rescue => "Rescue",
            QuestType.Hunt => "Hunt",
            QuestType.Escort => "Escort",
            QuestType.Boss => "Conquest",
            QuestType.Timed => "Challenge",
            _ => "Quest"
        };
        
        return $"{difficultyPrefix} {typeName}";
    }
    
    private string GenerateQuestDescription(string template)
    {
        return template
            .Replace("{count}", (_rng.Next(5, 20)).ToString())
            .Replace("{enemy}", _enemyTypes[_rng.Next(_enemyTypes.Length)])
            .Replace("{item}", _itemTypes[_rng.Next(_itemTypes.Length)])
            .Replace("{location}", _locations[_rng.Next(_locations.Length)])
            .Replace("{npc}", _npcNames[_rng.Next(_npcNames.Length)])
            .Replace("{time}", (_rng.Next(60, 300)).ToString());
    }
    
    private string GetRandomTarget(QuestType type)
    {
        return type switch
        {
            QuestType.Combat or QuestType.Hunt or QuestType.Boss => _enemyTypes[_rng.Next(_enemyTypes.Length)],
            QuestType.Collection => _itemTypes[_rng.Next(_itemTypes.Length)],
            QuestType.Exploration => _locations[_rng.Next(_locations.Length)],
            _ => _locations[_rng.Next(_locations.Length)]
        };
    }
    
    // Generate daily quest pool
    public void GenerateDailyQuests()
    {
        _availableQuests.Clear();
        
        // Generate 3-5 quests per day
        int questCount = 3 + _rng.Next(3);
        for (int i = 0; i < questCount; i++)
        {
            var type = (QuestType)_rng.Next(10);
            var difficulty = (QuestDifficulty)GetDifficultyWeight();
            var quest = GenerateQuest(type, difficulty);
            _availableQuests.Add(quest);
            EmitSignal(SignalName.QuestGenerated, quest);
        }
    }
    
    private int GetDifficultyWeight()
    {
        int roll = _rng.Next(100);
        if (roll < 30) return 0; // Easy 30%
        if (roll < 60) return 1; // Medium 30%
        if (roll < 80) return 2; // Hard 20%
        if (roll < 95) return 3; // Epic 15%
        return 4; // Legendary 5%
    }
    
    // Quest management
    public bool StartQuest(string questId)
    {
        var quest = _availableQuests.Find(q => q.Id == questId);
        if (quest == null) return false;
        
        quest.Status = QuestStatus.Active;
        quest.StartTime = DateTime.Now;
        _availableQuests.Remove(quest);
        _activeQuests.Add(quest);
        
        EmitSignal(SignalName.QuestStarted, quest);
        return true;
    }
    
    public void UpdateQuestProgress(string targetId, int amount = 1)
    {
        foreach (var quest in _activeQuests)
        {
            if (quest.TargetId == targetId || quest.TargetId == "Any")
            {
                quest.CurrentProgress = Mathf.Min(quest.CurrentProgress + amount, quest.TargetCount);
                EmitSignal(SignalName.QuestProgress, quest, quest.CurrentProgress);
                
                if (quest.CurrentProgress >= quest.TargetCount)
                {
                    CompleteQuest(quest.Id);
                }
            }
        }
    }
    
    public bool CompleteQuest(string questId)
    {
        var quest = _activeQuests.Find(q => q.Id == questId);
        if (quest == null) return false;
        
        quest.Status = QuestStatus.Completed;
        _activeQuests.Remove(quest);
        _completedQuests.Add(quest);
        
        // Award rewards
        if (PlayerStats.Instance != null)
        {
            PlayerStats.Instance.AddGold(quest.RewardGold);
            PlayerStats.Instance.AddExp(quest.RewardExp);
        }
        
        EmitSignal(SignalName.QuestCompleted, quest);
        return true;
    }
    
    public bool FailQuest(string questId)
    {
        var quest = _activeQuests.Find(q => q.Id == questId);
        if (quest == null) return false;
        
        quest.Status = QuestStatus.Failed;
        _activeQuests.Remove(quest);
        _failedQuests.Add(quest);
        
        EmitSignal(SignalName.QuestFailed, quest);
        return true;
    }
    
    // Check timed quests
    private void CheckTimedQuests()
    {
        var questsToFail = new List<string>();
        
        foreach (var quest in _activeQuests)
        {
            if (quest.TimeLimit > 0)
            {
                var elapsed = (DateTime.Now - quest.StartTime).TotalSeconds;
                if (elapsed > quest.TimeLimit)
                {
                    questsToFail.Add(quest.Id);
                }
            }
        }
        
        foreach (var questId in questsToFail)
        {
            FailQuest(questId);
        }
    }
    
    // Getters
    public List<Quest> GetAvailableQuests() => _availableQuests;
    public List<Quest> GetActiveQuests() => _activeQuests;
    public List<Quest> GetCompletedQuests() => _completedQuests;
    public List<Quest> GetFailedQuests() => _failedQuests;
}
